version: "3.9"

services:

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/:/etc/nginx/templates/
      - ./certs:/etc/certs
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
      - "DOMAIN=${DOMAIN}"
    depends_on:
      - wordpress
    restart: always

  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME}-mysql
    volumes:
      - ./mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always

  wordpress:
    depends_on:
    - mysql
    image: wordpress:latest
    container_name: ${APP_NAME}-wordpress
    restart: always
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./wordpress:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      PHP_INI_UPLOAD_MAX_FILESIZE: 256M

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    volumes:
      - ./config/phpmyadmin.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - '8080:80'
    links:
      - mysql:mysql
  
  db:
    image: postgres:alpine3.17
    container_name: ${APP_NAME}-postgres
    volumes:
      - mydb-data:/var/lib/postgresql/data
    env_file:
      - .env
  
  django_app:
    build: .
    container_name: ${APP_NAME}-django
    volumes:
      - static_vol:/app/static
      - media_vol:/app/media
      - ./src:/app
    command: python manage.py runserver 0.0.0.0:9000
    ports:
      - '9000:9000'
    env_file:
      - .env
    depends_on:
      - db


volumes:
  wordpress:
  mysql-db:
  mydb-data:
  static_vol:
  media_vol: